// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_XJ-kZn44Vp34EmIL9g0dUKWFqgDNomo',
    appId: '1:108251227639:web:99e0b71897f87a2c1efaf2',
    messagingSenderId: '108251227639',
    projectId: 'flutter-login-app-e90e9',
    authDomain: 'flutter-login-app-e90e9.firebaseapp.com',
    storageBucket: 'flutter-login-app-e90e9.appspot.com',
    measurementId: 'G-LQTVE8SK8B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD_-K26T1wr-vnsGavXn7zwW3iNZSlMWA',
    appId: '1:108251227639:android:25703912e7abbf3a1efaf2',
    messagingSenderId: '108251227639',
    projectId: 'flutter-login-app-e90e9',
    storageBucket: 'flutter-login-app-e90e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw9CGzfKx0zXCRfrkjCN6EfGtuqUGLJks',
    appId: '1:108251227639:ios:9652b85554e065fb1efaf2',
    messagingSenderId: '108251227639',
    projectId: 'flutter-login-app-e90e9',
    storageBucket: 'flutter-login-app-e90e9.appspot.com',
    iosClientId: '108251227639-inc1g7b0oje59vvkk7ljrndgnt7jrp5h.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCw9CGzfKx0zXCRfrkjCN6EfGtuqUGLJks',
    appId: '1:108251227639:ios:9652b85554e065fb1efaf2',
    messagingSenderId: '108251227639',
    projectId: 'flutter-login-app-e90e9',
    storageBucket: 'flutter-login-app-e90e9.appspot.com',
    iosClientId: '108251227639-inc1g7b0oje59vvkk7ljrndgnt7jrp5h.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginProject',
  );
}
